### ISSUE TITLE
Error: "Error: no URL specified!"

### ISSUE THREAD

**Issue by VaniSachdev** [curlconverter/curlconverter#423] opened 2022-08-03 22:26 UTC
**Input**:

```sh
curl \
  -H "Accept: application/vnd.github+json" \ 
  -H "Authorization: token <TOKEN>" \
  https://api.github.com/repos/OWNER/REPO/contents/PATH
```

**Comment by verhovsky** [comment] 2022-08-04 00:09
```
  -H "Accept: application/vnd.github+json" \ 
```

has a trailing space. Dupe of #420

**Closed by verhovsky** 2022-08-04 00:09 UTC
