### ISSUE TITLE
conversion is not working for a certain types

### ISSUE THREAD

**Issue by anagilla** [curlconverter/curlconverter#214] opened 2020-05-07 14:52 UTC
curl -s -X POST "http://$DomainHostName:$ROHPort/DataIntegrationService/modules/core/v1/applications/$applicationName/state" -H  "accept:application/json" -H  "username:$domainUserName" -H  "encryptedpassword:$domainEncryptedPassword" -H  "securitydomain:$DomainName" -H  "Content-Type:application/json" -d "{  \"action\": \"stop\"}"

**Comment by romadrutskii** [comment] 2020-08-09 13:25
> 
> 
> curl -s -X POST "http://$DomainHostName:$ROHPort/DataIntegrationService/modules/core/v1/applications/$applicationName/state" -H "accept:application/json" -H "username:$domainUserName" -H "encryptedpassword:$domainEncryptedPassword" -H "securitydomain:$DomainName" -H "Content-Type:application/json" -d "{ "action": "stop"}"

Could you please clarify the issue?

**Comment by verhovsky** [comment] 2022-12-30 07:17
Closing this as a duplicate of #226

**Closed by verhovsky** 2022-12-30 07:17 UTC
Labels: incorrect output, needs more information
