### ISSUE TITLE
multipart text need not "\"" in rust

### ISSUE THREAD

**Issue by mosttt** [curlconverter/curlconverter#537] opened 2023-03-24 08:29 UTC
```
 let form = multipart::Form::new()
        .text("token", "\"9d96b4efa6c9cec36d10055ccb943542\"")
```
should be replaced to
```
 let form = multipart::Form::new()
        .text("token", "9d96b4efa6c9cec36d10055ccb943542")
```

**Comment by mosttt** [comment] 2023-03-25 09:28
```
curl --location --request POST 'http://192.168.1.1/cgi-bin/luci/admin/network/network/wan' \
--form 'token="9d96b4efa6c9cec36d10055ccb943541"' \
--form 'cbi.submit="1"' \
--form 'tab.network.wan="general"' \
--form 'cbid.network.wan._fwzone="wan"' \
--form 'cbid.network.wan._fwzone.newzone=""' \
--form 'cbi.cbe.network.wan.ifname_single="1"' \
--form 'cbid.network.wan.ifname_single="eth0.2"' \
--form 'cbid.network.wan.proto="pppoe"' \
--form 'cbid.network.wan.ac=""' \
--form 'cbid.network.wan.service=""' \
--form 'cbi.cbe.network.wan.auto="1"' \
--form 'cbid.network.wan.auto="1"' \
--form 'cbi.cbe.network.wan.delegate="1"' \
--form 'cbid.network.wan.delegate="1"' \
--form 'cbi.cbe.network.wan.force_link="1"' \
--form 'cbid.network.wan.ipv6="auto"' \
--form 'cbi.cbe.network.wan.defaultroute="1"' \
--form 'cbid.network.wan.defaultroute="1"' \
--form 'cbid.network.wan.metric="0"' \
--form 'cbi.cbe.network.wan.peerdns="1"' \
--form 'cbid.network.wan.peerdns="1"' \
--form 'cbid.network.wan._keepalive_failure=""' \
--form 'cbid.network.wan._keepalive_interval=""' \
--form 'cbid.network.wan.demand=""' \
--form 'cbid.network.wan.mtu=""' \
--form 'cbi.apply="保存&应用"'
```
generate this in rust:

```
extern crate reqwest;
use reqwest::blocking::multipart;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let form = multipart::Form::new()
        .text("token", "\"9d96b4efa6c9cec36d10055ccb943541\"")
        .text("cbi.submit", "\"1\"")
        .text("tab.network.wan", "\"general\"")
        .text("cbid.network.wan._fwzone", "\"wan\"")
        .text("cbid.network.wan._fwzone.newzone", "\"\"")
        .text("cbi.cbe.network.wan.ifname_single", "\"1\"")
        .text("cbid.network.wan.ifname_single", "\"eth0.2\"")
        .text("cbid.network.wan.proto", "\"pppoe\"")
        .text("cbid.network.wan.ac", "\"\"")
        .text("cbid.network.wan.service", "\"\"")
        .text("cbi.cbe.network.wan.auto", "\"1\"")
        .text("cbid.network.wan.auto", "\"1\"")
        .text("cbi.cbe.network.wan.delegate", "\"1\"")
        .text("cbid.network.wan.delegate", "\"1\"")
        .text("cbi.cbe.network.wan.force_link", "\"1\"")
        .text("cbid.network.wan.ipv6", "\"auto\"")
        .text("cbi.cbe.network.wan.defaultroute", "\"1\"")
        .text("cbid.network.wan.defaultroute", "\"1\"")
        .text("cbid.network.wan.metric", "\"0\"")
        .text("cbi.cbe.network.wan.peerdns", "\"1\"")
        .text("cbid.network.wan.peerdns", "\"1\"")
        .text("cbid.network.wan._keepalive_failure", "\"\"")
        .text("cbid.network.wan._keepalive_interval", "\"\"")
        .text("cbid.network.wan.demand", "\"\"")
        .text("cbid.network.wan.mtu", "\"\"")
        .text("cbi.apply", "\"保存&应用\"");

    let client = reqwest::blocking::Client::new();
    let res = client.post("http://192.168.1.1/cgi-bin/luci/admin/network/network/wan")
        .multipart(form)
        .send()?
        .text()?;
    println!("{}", res);

    Ok(())
}
```
### **An extra quote was generated，but the function text already includes the `"` in the crate reqwest**

**Comment by verhovsky** [comment] 2023-04-06 19:06
Duplicate of #217

**Closed by verhovsky** 2023-04-06 19:06 UTC
