### ISSUE TITLE
Support username:password in URL

### ISSUE THREAD

**Issue by kishore0709** [curlconverter/curlconverter#77] opened 2018-01-02 12:55 UTC
Hi Nick,

I'm not able to convert below curl command to python requests. Could you please help in resolve this.  Thanks!

curl -XPUT username:password@localhost:port/_snapshot/my_backup -d '{ "type": "swift", "settings": { "swift_url": "http://someurl.com:port", "
swift_container": "backup", "swift_username": "test", "swift_password": "testing" }}'

**Comment by NickCarneiro** [comment] 2018-01-02 15:10
It looks like we don't supprt username:password in the url like you'd
expect. It works if you rework it a little:
curl -XPUT http://localhost:port/_snapshot/my_backup -u username:password
-d '{ "type": "swift", "settings": { "swift_url": "http://someurl.com:port",
"
swift_container": "backup", "swift_username": "test", "swift_password":
"testing" }}'

import requests

data = '{ "type": "swift", "settings": { "swift_url":
"http://someurl.com:port", "\nswift_container": "backup", "swift_username":
"test", "swift_password": "testing" }}'

response = requests.post('http://localhost/:port/_snapshot/my_backup',
data=data, auth=('username', 'password'))

**Comment by verhovsky** [comment] 2022-04-22 09:25
Closing as duplicate of #222

**Closed by verhovsky** 2022-04-22 09:25 UTC
Labels: enhancement, incorrect output
