### ISSUE TITLE
Please multidata support in [python] atleast

### ISSUE THREAD

**Issue by sneedgers** [curlconverter/curlconverter#421] opened 2022-07-25 21:33 UTC
Hello you can use 
from requests_toolbelt import MultipartEncoder
in python

```py
from requests_toolbelt import MultipartEncoder

data={
    'catid_cuteness': f'{threadId}',
    'breed': 'T',
    'unixid': f'{comment}',
    'json_response': '1',
    'file_av1': 'undefined',
}

m = MultipartEncoder(
    fields=data
)
headers = {
    'Connection': 'keep-alive',
    'Pragma': 'no-cache',
    'Cache-Control': 'no-cache',
    'Accept': '*/*',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4324.150 Safari/537.36',
    'Content-Type': m.content_type,
    'Sec-Fetch-Site': 'same-site',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Dest': 'empty',
    'Accept-Language': 'en-US,en;q=0.9',
}
r = s.post("https://catlocalhost/post.php",headers=headers,data=m)
```

![image](https://user-images.githubusercontent.com/107140768/180877626-d08f5c54-8062-41ad-b2fb-ffa10e68c885.png)
I dont want it to look like this 
I want the multidata to be read by this tool. and parsed with MultipartEncoder

THANKS FOR EVERYTHING

**Comment by verhovsky** [comment] 2022-07-26 08:15
Please paste your input curl command.

**Comment by verhovsky** [comment] 2023-01-07 12:57
Closing as duplicate of #457

**Closed by verhovsky** 2023-01-07 12:57 UTC
