### ISSUE TITLE
Angular import error in node modules

### ISSUE THREAD

**Issue by Anil-Bhimwal1** [curlconverter/curlconverter#451] opened 2022-09-29 05:49 UTC
<img width="1287" alt="Screenshot 2022-09-29 at 11 19 38 AM" src="https://user-images.githubusercontent.com/70019507/192949489-5e9b67a2-aea1-443b-8b12-18ff156159d2.png">
I am trying use this library in my angular project but its giving me this error at build time

**Comment by Anil-Bhimwal1** [comment] 2022-09-29 05:50
node version: 14
angular version: 7.3.5
please help

**Comment by verhovsky** [comment] 2023-04-15 01:38
Going to close this because I can't reproduce it. Please post instructions for how I can encounter this error on my own computer because otherwise I have no idea what you're trying to do here and no ability to debug the issue. I can't intuit what is going on in your computer from a single screenshot of an error message.

**Closed by verhovsky** 2023-04-15 01:38 UTC
Labels: installation issue
